---
- name: obsidian role
  tags:
    - obsidian
  block:

  # flatpak
  - name: Flatpak state {{ obsidian_flatpak_state }}
    become: true
    community.general.flatpak:
      name: md.obsidian.Obsidian
      method: "{{ obsidian_flatpak_scope }}" 
      state: "{{ obsidian_flatpak_state }}"

  # config
  - when: 
    - obsidian_config_src != None
    - obsidian_config_dst != None
    - obsidian_user != None
    block:
    
    # mkdir dest_dir
    - name: Mkdir {{ obsidian_config_dst }}
      become: true
      ansible.builtin.file:
        path: "{{ obsidian_config_dst }}"
        state: directory
        owner: "{{ obsidian_user }}"
        group: "{{ obsidian_user }}"
        mode: u=rwx,g=,o=

    # copy config
    - name: Copy config {{ obsidian_config_src }} to {{ obsidian_config_dst }}
      become: true
      ansible.builtin.copy:
        src: "{{ obsidian_config_src }}/"
        dest: "{{ obsidian_config_dst }}"
        owner: "{{ obsidian_user }}"
        group: "{{ obsidian_user }}"
        mode: u=rw,g=,o=